application: pachalerts
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/xmpp/.*
  script: xmpp.py

- url: /.*
  script: main.py

